app_launcher_cmd = "hyprlauncher"

[modules]
left = [ "AppLauncher", "MediaPlayer" ]
center = [ "Clock" ]
right = [ "SystemInfo", "Tray", [ "Workspaces", "Privacy", "Settings" ] ]

[appearance]
success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = [ "#cba6f7", "#b4befe", "#74c7ec" ]

[appearance.primary_color]
base = "#cba6f7"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#b4befe"

